### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by hidakatsuya**
## Abstract

Both generator and editor have some unreleased changes. I propose to release v0.11.0.

## Release Steps

I wrote the release steps. This Pullrequest also follows the steps.

## Testing the built packages for each platform

You can download the built packages:
https://github.com/thinreports/thinreports-editor/actions/runs/138679094

- [x] macos
- [x] linux
- [x] windows

@maeda-m Could you test the package for windows?

## Other tasks

- [x] Create pullrequest for releasing generator v0.11.0 https://github.com/thinreports/thinreports-generator/pull/105

### CODE REVIEW

**Comment by maeda-m** [comment]
@hidakatsuya 
The test results were fine.

1. the logo be displayed in splash
2. open PNG files with the Image Tool
3. saving and opening TLF files

**Comment by hidakatsuya** [comment]
thx!

**Comment by hidakatsuya** [comment]
@maeda-m 
I created [a PR to release generator v0.11.0](https://github.com/thinreports/thinreports-generator/pull/105). Please also review the PR.

**Comment by hidakatsuya** [comment]
@maeda-m 
Editor v0.11.0 and Generator v0.11.0 are ready for release. May I release these today (Jun 20)?

**Comment by maeda-m** [comment]
@hidakatsuya 
Of course. What do you want me to do?

**Comment by hidakatsuya** [comment]
@maeda-m Ok, i'll release them today.

**Pull request merged**
