### PR TITLE
Fixed #45 Does not launch in unsupported language

### LINKED ISSUE #45: Google Chrome on Ubuntu 14.10 Not run
Hiyas i have install the editor in Google chrome and next i click to run it apper the splash but dont do naffin more :(

Sorry me english is bad
captura de pantalla de 2015-05-01 18 40 12

### PR DESCRIPTION
**Pull request by hidakatsuya**
I have modified to set English by default in any languages except Japanese and English.

### CODE REVIEW

**Comment by hidakatsuya** [comment]
@maeda-m Please check, but do not merge.

**Comment by maeda-m** [comment]
@hidakatsuya 
It was confirmed that can be launch successfully in my Spanish environment.

**Comment by hidakatsuya** [comment]
@obelich We have fixed #45. Could you check whether it works correctly in your environment? If possible, please try to start Thinreports Editor (Development ver) in the following steps:

  1. Click the "Download ZIP" button in the following page to get the source code (ZIP file):
https://github.com/hidakatsuya/thinreports-editor/tree/fix-issue45
  2. Unzip the ZIP file to any directory
  3. Start your Chrome Browser, and open Chrome Extensions page (chrome://extensions/)
  4. Click the "Load unpacked extension..." button, and select "src" directory within the directory where you unzipped
  5. Click the "Launch" button to try to launch Thinreports Editor (Development ver)

**Comment by obelich** [comment]
Ok let me check downloading :)

**Comment by obelich** [comment]
I get that error :(

captura de pantalla de 2015-05-17 12 54 30

**Comment by obelich** [comment]
im compile ruby in my computer i dont install using rvm or apt

**Comment by maeda-m** [comment]
@obelich "ZIP file" does not include the "git submodule", please to clone the source code with this command:
`git clone -b fix-issue45 --recursive https://github.com/hidakatsuya/thinreports-editor.git`

**Comment by hidakatsuya** [comment]
@obelich Sorry. the ZIP file has not included a part of necessary Code like @maeda-m say. Please get the source code using `Git` as below:

    $ git clone -b fix-issue45 --recursive https://github.com/hidakatsuya/thinreports-editor.git

**Comment by obelich** [comment]
Yep i have download that using git but give that error

2015-05-18 21:00 GMT-07:00 Katsuya HIDAKA <notifications@github.com>:

**Comment by hidakatsuya** [comment]
@obelich Thank you for reply. What is that error?

**Comment by hidakatsuya** [comment]
@obelich We could not know cause of the error you got, but we have decided to release the fixed version. Thank you very much for your cooperation!

**Pull request merged**
